// apps/dialogue/app/components/chat/ChatContainer.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useI18n } from '~/i18n';
import { generateId, type Message, useChatStore } from '~/stores';
import { ChatInput } from './ChatInput';
import { ChatMessage } from './ChatMessage';

export function ChatContainer() {
  const { t } = useI18n();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [isThinking, setIsThinking] = useState(false);
  const [localMessages, setLocalMessages] = useState<Message[]>([]);

  const {
    isHydrated,
    ghostMode,
    activeConversationId,
    getActiveConversation,
    createConversation,
    addMessage,
    clearActive,
  } = useChatStore();

  // Get messages from active conversation or local state (ghost mode)
  const activeConversation = getActiveConversation();
  const messages = ghostMode ? localMessages : (activeConversation?.messages ?? []);

  // Initialize with welcome message
  useEffect(() => {
    if (!isHydrated) return;

    // If no active conversation and not ghost mode, create one
    if (!activeConversationId && !ghostMode) {
      const welcomeMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.welcome,
        timestamp: Date.now(),
      };
      createConversation(welcomeMessage);
    }

    // If ghost mode, initialize with welcome message
    if (ghostMode && localMessages.length === 0) {
      setLocalMessages([
        {
          id: generateId(),
          role: 'assistant',
          content: t.welcome,
          timestamp: Date.now(),
        },
      ]);
    }
  }, [
    isHydrated,
    activeConversationId,
    ghostMode,
    t.welcome,
    createConversation,
    localMessages.length,
  ]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Handle sending a message
  const handleSend = useCallback(
    async (content: string) => {
      const userMessage: Message = {
        id: generateId(),
        role: 'user',
        content,
        timestamp: Date.now(),
      };

      if (ghostMode) {
        setLocalMessages((prev) => [...prev, userMessage]);
      } else {
        addMessage(userMessage);
      }

      setIsThinking(true);

      // Simulate response (replace with actual knowledge search)
      await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 500));

      const assistantMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.noResults,
        timestamp: Date.now(),
      };

      if (ghostMode) {
        setLocalMessages((prev) => [...prev, assistantMessage]);
      } else {
        addMessage(assistantMessage);
      }

      setIsThinking(false);
    },
    [ghostMode, addMessage, t.noResults],
  );

  // Handle new chat
  const handleNewChat = useCallback(() => {
    if (ghostMode) {
      setLocalMessages([
        {
          id: generateId(),
          role: 'assistant',
          content: t.welcome,
          timestamp: Date.now(),
        },
      ]);
    } else {
      clearActive();
      const welcomeMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.welcome,
        timestamp: Date.now(),
      };
      createConversation(welcomeMessage);
    }
  }, [ghostMode, clearActive, createConversation, t.welcome]);

  // Show loading state while hydrating
  if (!isHydrated) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <div className="animate-pulse text-gray-400">{t.thinking}</div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
        <div>
          <h1 className="text-xl font-semibold">{t.title}</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">{t.subtitle}</p>
        </div>
        <div className="flex items-center gap-2">
          {ghostMode && (
            <span className="px-2 py-1 text-xs bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 rounded">
              {t.ghostMode}
            </span>
          )}
          <button
            type="button"
            onClick={handleNewChat}
            className="px-3 py-1.5 text-sm bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            {t.newChat}
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <ChatMessage key={message.id} message={message} />
        ))}
        {isThinking && (
          <div className="flex gap-3">
            <div className="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center shrink-0 text-sm font-medium text-gray-600 dark:text-gray-300">
              D
            </div>
            <div className="px-4 py-2 bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-bl-md">
              <span className="animate-pulse">{t.thinking}</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-200 dark:border-gray-700">
        <ChatInput onSend={handleSend} disabled={isThinking} />
      </div>
    </div>
  );
}

// apps/dialogue-solid-backup/src/components/chat/ChatContainer.tsx
import { useLocation, useNavigate, useParams } from '@solidjs/router';
import type { Component } from 'solid-js';
import { createEffect, createSignal, For, onMount, Show } from 'solid-js';
import { useI18n } from '~/i18n';
import { translations } from '~/i18n/translations';
import { handleDynamicQuery } from '~/lib/handlers';
import { detectLanguage } from '~/lib/language-detector';
import { searchKnowledge } from '~/lib/search';
import type { Message } from '~/stores/chat-store';
import { chatActions, chatStore, generateId } from '~/stores/chat-store';
import { ChatInput } from '../ChatInput';
import { ChatMessage } from '../ChatMessage';

// ========================================
// ChatContainer Component - 채팅 컨테이너
// ========================================

interface ChatContainerProps {
  onNewChat?: () => void;
  resetTrigger?: number;
  loadTrigger?: number;
}

export const ChatContainer: Component<ChatContainerProps> = (props) => {
  const { t, locale } = useI18n();
  const navigate = useNavigate();
  const location = useLocation();
  const params = useParams<{ id?: string }>();
  const [messages, setMessages] = createSignal<Message[]>([]);
  const [isThinking, setIsThinking] = createSignal(false);
  let messagesEndRef: HTMLDivElement | undefined;

  // Track previous trigger values to detect actual changes
  let prevResetTrigger = 0;
  let prevLoadTrigger = 0;

  // Helper to get localized chat path
  const getChatPath = (id: string) => {
    const isKorean = location.pathname.startsWith('/ko');
    return isKorean ? `/ko/c/${id}` : `/c/${id}`;
  };

  // Helper to get home path
  const getHomePath = () => {
    const isKorean = location.pathname.startsWith('/ko');
    return isKorean ? '/ko' : '/';
  };

  // Initialize with welcome message
  const initializeChat = () => {
    // Clear active conversation FIRST to prevent race conditions
    // 먼저 활성 대화를 클리어하여 race condition 방지
    chatActions.clearActive();

    const welcomeMessage: Message = {
      id: generateId(),
      role: 'assistant',
      content: t.welcome,
      timestamp: Date.now(),
    };
    setMessages([welcomeMessage]);
  };

  onMount(() => {
    // Hydrate chat store first
    chatActions.hydrate();
    initializeChat();
  });

  // Handle URL params for conversation loading (from /c/:id or /ko/c/:id routes)
  createEffect(() => {
    if (!chatStore.isHydrated) return;

    const conversationId = params.id;
    if (!conversationId) return;

    // Try to load the conversation from URL
    const conversation = chatActions.loadConversation(conversationId);

    // If conversation not found, redirect to home
    if (!conversation) {
      navigate(getHomePath(), { replace: true });
    }
  });

  // Scroll to bottom when messages change
  createEffect(() => {
    if (messagesEndRef && messages().length > 0) {
      messagesEndRef.scrollIntoView({ behavior: 'smooth' });
    }
  });

  // Load conversation when activeConversationId changes (from route or sidebar)
  // Track previous active ID to detect actual changes
  let prevActiveId: string | null = null;

  createEffect(() => {
    const isHydrated = chatStore.isHydrated;
    if (!isHydrated) return;

    const activeId = chatStore.activeConversationId;

    // Only react to actual ID changes
    if (activeId === prevActiveId) return;
    prevActiveId = activeId;

    if (activeId) {
      const conversation = chatStore.conversations.find((c) => c.id === activeId);
      if (conversation && conversation.messages.length > 0) {
        setMessages([...conversation.messages]);
      }
    }
  });

  // Also handle explicit load trigger from sidebar (for backwards compatibility)
  createEffect(() => {
    const trigger = props.loadTrigger ?? 0;
    if (trigger <= prevLoadTrigger) return;
    prevLoadTrigger = trigger;
    // The activeConversationId effect above will handle the actual loading
  });

  const resetChat = () => {
    initializeChat();
    // Navigate to home when starting new chat
    const currentPath = location.pathname;
    const homePath = getHomePath();
    if (currentPath !== homePath && currentPath !== `${homePath}/`) {
      navigate(homePath, { replace: true });
    }
    props.onNewChat?.();
  };

  // Listen for reset trigger from parent (only when actually changed)
  createEffect(() => {
    const trigger = props.resetTrigger ?? 0;
    if (trigger > prevResetTrigger) {
      prevResetTrigger = trigger;
      resetChat();
    }
  });

  const handleSend = async (content: string) => {
    const userMessage: Message = {
      id: generateId(),
      role: 'user',
      content,
      timestamp: Date.now(),
    };

    // Start a new conversation if needed (not in ghost mode)
    // Use activeConversationId check instead of conversationStarted for atomicity
    // conversationStarted 대신 activeConversationId 체크하여 원자성 보장
    if (!chatStore.activeConversationId && !chatStore.ghostMode) {
      const welcomeMsg = messages()[0];
      if (welcomeMsg) {
        const newConversation = chatActions.createConversation(welcomeMsg);
        // Update URL to reflect new conversation
        if (newConversation) {
          navigate(getChatPath(newConversation.id), { replace: true });
        }
      }
    }

    setMessages((prev) => [...prev, userMessage]);

    // Save to store (only if not in ghost mode and has active conversation)
    if (!chatStore.ghostMode && chatStore.activeConversationId) {
      chatActions.addMessage(userMessage);
    }

    setIsThinking(true);

    await new Promise((resolve) => setTimeout(resolve, 300));

    // Detect language from user input (fallback to URL locale)
    const detectedLocale = detectLanguage(content, locale());
    const localizedT = translations[detectedLocale].app;

    let responseContent: string;

    const dynamicResult = handleDynamicQuery(content, detectedLocale);

    if (dynamicResult.matched) {
      if (dynamicResult.isAsync && dynamicResult.asyncResponse) {
        responseContent = await dynamicResult.asyncResponse();
      } else {
        responseContent = dynamicResult.response || localizedT.noResults;
      }
    } else {
      const results = searchKnowledge(content, detectedLocale);

      if (results.length > 0 && results[0]) {
        responseContent = results[0].answer;
      } else {
        responseContent = localizedT.noResults;
      }
    }

    const assistantMessage: Message = {
      id: generateId(),
      role: 'assistant',
      content: responseContent,
      timestamp: Date.now(),
    };

    setIsThinking(false);
    setMessages((prev) => [...prev, assistantMessage]);

    // Save to store (only if not in ghost mode and has active conversation)
    if (!chatStore.ghostMode && chatStore.activeConversationId) {
      chatActions.addMessage(assistantMessage);
    }
  };

  return (
    <div class="flex h-full flex-col bg-bg-chat">
      {/* Header */}
      <div class="flex items-center justify-between border-b border-border bg-bg-secondary px-4 py-3">
        <div class="flex items-center gap-2">
          <h2 class="font-semibold text-sm text-text-primary">{t.title}</h2>
          <Show when={chatStore.ghostMode}>
            <span class="px-2 py-0.5 text-xs font-medium bg-purple-500/20 text-purple-400 rounded-full">
              {t.ghostMode}
            </span>
          </Show>
        </div>
      </div>

      {/* Messages */}
      <div class="flex-1 overflow-y-auto py-4">
        <For each={messages()}>{(message) => <ChatMessage message={message} />}</For>

        {isThinking() && (
          <div class="flex items-center gap-3 px-6 py-4 animate-fade-in">
            <div class="flex gap-1">
              <span
                class="w-2 h-2 bg-accent rounded-full animate-typing"
                style="animation-delay: 0s"
              />
              <span
                class="w-2 h-2 bg-accent rounded-full animate-typing"
                style="animation-delay: 0.2s"
              />
              <span
                class="w-2 h-2 bg-accent rounded-full animate-typing"
                style="animation-delay: 0.4s"
              />
            </div>
            <span class="text-text-muted text-sm">{t.thinking}</span>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <ChatInput onSend={handleSend} disabled={isThinking()} />
    </div>
  );
};

// Re-export for convenience
export { ChatContainer as default };
