// apps/tools/src/components/chat/ChatMessage.tsx
import type { Component } from 'solid-js';
import { useLanguage } from '@/i18n';
import { cn } from '@/lib/utils';
import type { Message } from '@/stores/chat-store';

// ========================================
// ChatMessage Component - 개별 채팅 메시지
// ========================================

interface ChatMessageProps {
  message: Message;
}

export const ChatMessage: Component<ChatMessageProps> = (props) => {
  const { t } = useLanguage();
  const isBot = () => props.message.type === 'bot';

  // Get translated content for special messages (e.g., welcome message)
  const getContent = () => {
    if (props.message.id === 'welcome') {
      return t().chat.welcome;
    }
    return props.message.content;
  };

  return (
    <div class={cn('flex w-full', isBot() ? 'justify-start' : 'justify-end')}>
      <div
        class={cn(
          'max-w-[85%] rounded-2xl px-4 py-2 text-sm',
          isBot()
            ? 'bg-muted text-foreground rounded-bl-md'
            : 'bg-primary text-primary-foreground rounded-br-md'
        )}
      >
        <p class="whitespace-pre-wrap break-words">{getContent()}</p>
      </div>
    </div>
  );
};

// apps/dialogue/app/components/chat/ChatMessage.tsx
import type { Message } from '~/stores';

interface ChatMessageProps {
  message: Message;
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isUser = message.role === 'user';

  return (
    <div
      className={`flex gap-4 animate-[fadeIn_0.3s_ease-out] ${isUser ? 'flex-row-reverse' : 'flex-row'}`}
    >
      {/* Avatar */}
      <div
        className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-sm font-medium ${
          isUser
            ? 'bg-(--color-accent-primary) text-white'
            : 'bg-(--color-bg-tertiary) text-(--color-text-secondary)'
        }`}
      >
        {isUser ? 'U' : 'D'}
      </div>

      {/* Message content */}
      <div
        className={`max-w-[80%] px-4 py-2 rounded-2xl ${
          isUser
            ? 'bg-(--color-accent-primary) text-white rounded-br-md'
            : 'bg-(--color-bg-tertiary) text-(--color-text-primary) rounded-bl-md'
        }`}
      >
        <p className="whitespace-pre-wrap break-words">{message.content}</p>
      </div>
    </div>
  );
}
