// apps/dialogue/src/components/chat/ChatContainer.tsx
import { Component, createSignal, For, createEffect, onMount } from "solid-js";
import { useI18n } from "~/i18n";
import { translations } from "~/i18n/translations";
import { searchKnowledge } from "~/lib/search";
import { handleDynamicQuery } from "~/lib/handlers";
import { detectLanguage } from "~/lib/language-detector";
import { ChatMessage, Message } from "../ChatMessage";
import { ChatInput } from "../ChatInput";

// ========================================
// ChatContainer Component - 채팅 컨테이너
// ========================================

function generateId(): string {
  return Date.now().toString(36) + Math.random().toString(36).substr(2);
}

interface ChatContainerProps {
  onNewChat?: () => void;
}

export const ChatContainer: Component<ChatContainerProps> = (props) => {
  const { t, locale } = useI18n();
  const [messages, setMessages] = createSignal<Message[]>([]);
  const [isThinking, setIsThinking] = createSignal(false);
  let messagesEndRef: HTMLDivElement | undefined;

  onMount(() => {
    const welcomeMessage: Message = {
      id: generateId(),
      role: "assistant",
      content: t.welcome,
      timestamp: Date.now(),
    };
    setMessages([welcomeMessage]);
  });

  createEffect(() => {
    if (messagesEndRef) {
      messagesEndRef.scrollIntoView({ behavior: "smooth" });
    }
  });

  const handleNewChat = () => {
    setMessages([
      {
        id: generateId(),
        role: "assistant",
        content: t.welcome,
        timestamp: Date.now(),
      },
    ]);
    props.onNewChat?.();
  };

  const handleSend = async (content: string) => {
    const userMessage: Message = {
      id: generateId(),
      role: "user",
      content,
      timestamp: Date.now(),
    };
    setMessages((prev) => [...prev, userMessage]);

    setIsThinking(true);

    await new Promise((resolve) => setTimeout(resolve, 300));

    // Detect language from user input (fallback to URL locale)
    const detectedLocale = detectLanguage(content, locale());
    const localizedT = translations[detectedLocale].app;

    let responseContent: string;

    const dynamicResult = handleDynamicQuery(content, detectedLocale);

    if (dynamicResult.matched) {
      if (dynamicResult.isAsync && dynamicResult.asyncResponse) {
        responseContent = await dynamicResult.asyncResponse();
      } else {
        responseContent = dynamicResult.response || localizedT.noResults;
      }
    } else {
      const results = searchKnowledge(content, detectedLocale);

      if (results.length > 0) {
        responseContent = results[0].answer;
      } else {
        responseContent = localizedT.noResults;
      }
    }

    const assistantMessage: Message = {
      id: generateId(),
      role: "assistant",
      content: responseContent,
      timestamp: Date.now(),
    };

    setIsThinking(false);
    setMessages((prev) => [...prev, assistantMessage]);
  };

  // Export handleNewChat for parent components
  (ChatContainer as any).handleNewChat = handleNewChat;

  return (
    <div class="flex h-full flex-col bg-bg-chat">
      {/* Header */}
      <div class="flex items-center justify-between border-b border-border bg-bg-secondary px-4 py-3">
        <h2 class="font-semibold text-sm text-text-primary">{t.title}</h2>
      </div>

      {/* Messages */}
      <div class="flex-1 overflow-y-auto py-4">
        <For each={messages()}>
          {(message) => <ChatMessage message={message} />}
        </For>

        {isThinking() && (
          <div class="flex items-center gap-3 px-6 py-4 animate-fade-in">
            <div class="flex gap-1">
              <span class="w-2 h-2 bg-accent rounded-full animate-typing" style="animation-delay: 0s" />
              <span class="w-2 h-2 bg-accent rounded-full animate-typing" style="animation-delay: 0.2s" />
              <span class="w-2 h-2 bg-accent rounded-full animate-typing" style="animation-delay: 0.4s" />
            </div>
            <span class="text-text-muted text-sm">{t.thinking}</span>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <ChatInput onSend={handleSend} disabled={isThinking()} />
    </div>
  );
};

// Re-export for convenience
export { ChatContainer as default };

// apps/dialogue/app/components/chat/ChatContainer.tsx
import { useCallback, useEffect, useRef, useState } from 'react';
import { useI18n } from '~/i18n';
import { generateId, type Message, useChatStore } from '~/stores';
import { ChatInput } from './ChatInput';
import { ChatMessage } from './ChatMessage';

export function ChatContainer() {
  const { t } = useI18n();
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const [isThinking, setIsThinking] = useState(false);
  const [localMessages, setLocalMessages] = useState<Message[]>([]);

  const {
    isHydrated,
    ghostMode,
    activeConversationId,
    getActiveConversation,
    createConversation,
    addMessage,
    clearActive,
  } = useChatStore();

  // Get messages from active conversation or local state (ghost mode)
  const activeConversation = getActiveConversation();
  const messages = ghostMode ? localMessages : (activeConversation?.messages ?? []);

  // Initialize with welcome message
  useEffect(() => {
    if (!isHydrated) return;

    // If no active conversation and not ghost mode, create one
    if (!activeConversationId && !ghostMode) {
      const welcomeMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.welcome,
        timestamp: Date.now(),
      };
      createConversation(welcomeMessage);
    }

    // If ghost mode, initialize with welcome message
    if (ghostMode && localMessages.length === 0) {
      setLocalMessages([
        {
          id: generateId(),
          role: 'assistant',
          content: t.welcome,
          timestamp: Date.now(),
        },
      ]);
    }
  }, [
    isHydrated,
    activeConversationId,
    ghostMode,
    t.welcome,
    createConversation,
    localMessages.length,
  ]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  // Handle sending a message
  const handleSend = useCallback(
    async (content: string) => {
      const userMessage: Message = {
        id: generateId(),
        role: 'user',
        content,
        timestamp: Date.now(),
      };

      if (ghostMode) {
        setLocalMessages((prev) => [...prev, userMessage]);
      } else {
        addMessage(userMessage);
      }

      setIsThinking(true);

      // Simulate response (replace with actual knowledge search)
      await new Promise((resolve) => setTimeout(resolve, 500 + Math.random() * 500));

      const assistantMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.noResults,
        timestamp: Date.now(),
      };

      if (ghostMode) {
        setLocalMessages((prev) => [...prev, assistantMessage]);
      } else {
        addMessage(assistantMessage);
      }

      setIsThinking(false);
    },
    [ghostMode, addMessage, t.noResults],
  );

  // Handle new chat
  const handleNewChat = useCallback(() => {
    if (ghostMode) {
      setLocalMessages([
        {
          id: generateId(),
          role: 'assistant',
          content: t.welcome,
          timestamp: Date.now(),
        },
      ]);
    } else {
      clearActive();
      const welcomeMessage: Message = {
        id: generateId(),
        role: 'assistant',
        content: t.welcome,
        timestamp: Date.now(),
      };
      createConversation(welcomeMessage);
    }
  }, [ghostMode, clearActive, createConversation, t.welcome]);

  // Show loading state while hydrating
  if (!isHydrated) {
    return (
      <div className="flex-1 flex items-center justify-center">
        <div className="animate-pulse text-gray-400">{t.thinking}</div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-gray-200 dark:border-gray-700">
        <div>
          <h1 className="text-xl font-semibold">{t.title}</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">{t.subtitle}</p>
        </div>
        <div className="flex items-center gap-2">
          {ghostMode && (
            <span className="px-2 py-1 text-xs bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 rounded">
              {t.ghostMode}
            </span>
          )}
          <button
            type="button"
            onClick={handleNewChat}
            className="px-3 py-1.5 text-sm bg-gray-100 dark:bg-gray-800 hover:bg-gray-200 dark:hover:bg-gray-700 rounded-lg transition-colors"
          >
            {t.newChat}
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((message) => (
          <ChatMessage key={message.id} message={message} />
        ))}
        {isThinking && (
          <div className="flex gap-3">
            <div className="w-8 h-8 rounded-full bg-gray-200 dark:bg-gray-700 flex items-center justify-center shrink-0 text-sm font-medium text-gray-600 dark:text-gray-300">
              D
            </div>
            <div className="px-4 py-2 bg-gray-100 dark:bg-gray-800 rounded-2xl rounded-bl-md">
              <span className="animate-pulse">{t.thinking}</span>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="p-4 border-t border-gray-200 dark:border-gray-700">
        <ChatInput onSend={handleSend} disabled={isThinking} />
      </div>
    </div>
  );
}
