// apps/sound-blue/src/routes/blog.tsx
import type { JSX } from 'solid-js';
import { NavigationLayout, PageSeo, useLanguage } from '~/components';

export default function BlogPage(): JSX.Element {
  const { t } = useLanguage();

  return (
    <>
      <PageSeo page="blog" />
      <NavigationLayout>
        <div class="max-w-4xl mx-auto px-4 py-8">
          <h1 class="text-3xl font-bold mb-8">{t().blog.title}</h1>

          <div class="prose prose-lg max-w-none">
            <p class="text-content-muted mb-6">{t().blog.description}</p>

            <div class="bg-surface-dim rounded-lg p-8 text-center">
              <p class="text-content-muted text-lg">{t().blog.comingSoon}</p>
            </div>
          </div>
        </div>
      </NavigationLayout>
    </>
  );
}

// apps/sound-blue/app/routes/($locale)/blog.tsx
import type { MetaFunction } from 'react-router';
import { NavigationLayout } from '~/components/layout';
import m from '~/lib/messages';
import { getSeoMeta } from '~/lib/seo';

export const meta: MetaFunction = ({ params }) => [
  { title: 'Blog | Sound Blue' },
  { name: 'description', content: "Sound Blue's blog." },
  ...getSeoMeta('/blog', params),
];

export default function Blog() {
  return (
    <NavigationLayout>
      <div className="max-w-3xl mx-auto p-6">
        <h1 className="text-3xl font-bold mb-4">{m['blog.title']()}</h1>
        <p className="text-content-muted">{m['blog.comingSoon']()}</p>
      </div>
    </NavigationLayout>
  );
}
