// apps/sound-blue-solid-backup/src/routes/sitemap.tsx
import { A } from '@solidjs/router';
import { For, type JSX } from 'solid-js';
import { NavigationLayout, PageSeo, useLanguage } from '~/components';
import { SmallExternalLinkIcon } from '~/constants';

interface InternalLink {
  path: string;
  labelKey:
    | 'home'
    | 'news'
    | 'blog'
    | 'builtWith'
    | 'privacy'
    | 'terms'
    | 'license'
    | 'soundRecording';
}

interface ExternalLink {
  url: string;
  label: string;
}

interface SitemapSection {
  titleKey: 'main' | 'content' | 'about' | 'legal' | 'external' | 'xml';
  external?: boolean;
  links: (InternalLink | ExternalLink)[];
}

const sections: SitemapSection[] = [
  {
    titleKey: 'main',
    links: [{ path: '/', labelKey: 'home' }],
  },
  {
    titleKey: 'content',
    links: [
      { path: '/news', labelKey: 'news' },
      { path: '/blog', labelKey: 'blog' },
    ],
  },
  {
    titleKey: 'about',
    links: [{ path: '/built-with', labelKey: 'builtWith' }],
  },
  {
    titleKey: 'legal',
    links: [
      { path: '/privacy', labelKey: 'privacy' },
      { path: '/terms', labelKey: 'terms' },
      { path: '/license', labelKey: 'license' },
      { path: '/sound-recording', labelKey: 'soundRecording' },
    ],
  },
  {
    titleKey: 'external',
    external: true,
    links: [
      { url: 'https://youtube.com/@SoundBlueMusic', label: 'YouTube' },
      { url: 'https://soundblue.music', label: 'Discography' },
    ],
  },
  {
    titleKey: 'xml',
    external: true,
    links: [{ url: '/sitemap.xml', label: 'sitemap.xml' }],
  },
];

export default function SitemapPage(): JSX.Element {
  const { t, localizedPath } = useLanguage();

  return (
    <>
      <PageSeo page="sitemap" />
      <NavigationLayout>
        <div class="max-w-4xl mx-auto px-4 py-8">
          <h1 class="text-3xl font-bold mb-8">{t().sitemap.title}</h1>

          <div class="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
            <For each={sections}>
              {(section) => (
                <div class="space-y-4">
                  <h2 class="text-xl font-semibold text-content">
                    {t().sitemap.sections[section.titleKey]}
                  </h2>
                  <ul class="space-y-2">
                    <For each={section.links}>
                      {(link) => (
                        <li>
                          {'path' in link ? (
                            <A
                              href={localizedPath(link.path)}
                              class="text-content-muted hover:text-content transition-colors"
                            >
                              {t().sitemap.links[link.labelKey]}
                            </A>
                          ) : (
                            <a
                              href={link.url}
                              target="_blank"
                              rel="noopener noreferrer"
                              class="text-content-muted hover:text-content transition-colors inline-flex items-center gap-1"
                            >
                              {link.label}
                              <SmallExternalLinkIcon class="w-3 h-3" />
                            </a>
                          )}
                        </li>
                      )}
                    </For>
                  </ul>
                </div>
              )}
            </For>
          </div>
        </div>
      </NavigationLayout>
    </>
  );
}

// apps/sound-blue/src/routes/ko/sitemap.tsx
import { createFileRoute, Link } from '@tanstack/react-router';
import { NavigationLayout } from '~/components/layout';
import m from '~/lib/messages';

export const Route = createFileRoute('/ko/sitemap')({
  head: () => ({
    meta: [
      { title: '사이트맵 | Sound Blue' },
      { name: 'description', content: 'Sound Blue 웹사이트의 전체 사이트맵입니다.' },
    ],
    links: [
      { rel: 'canonical', href: 'https://soundbluemusic.com/ko/sitemap' },
      { rel: 'alternate', hrefLang: 'ko', href: 'https://soundbluemusic.com/ko/sitemap' },
      { rel: 'alternate', hrefLang: 'en', href: 'https://soundbluemusic.com/sitemap' },
      { rel: 'alternate', hrefLang: 'x-default', href: 'https://soundbluemusic.com/sitemap' },
    ],
  }),
  component: Sitemap,
});

function Sitemap() {
  return (
    <NavigationLayout>
      <div className="max-w-3xl mx-auto p-6">
        <h1 className="text-3xl font-bold mb-8">{m['sitemap.title']()}</h1>
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4">{m['sitemap.sections.main']()}</h2>
          <ul className="space-y-2">
            <li>
              <Link to="/ko" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.home']()}
              </Link>
            </li>
            <li>
              <Link to="/ko/about" className="text-[var(--color-link)] hover:underline">
                {m['nav.about']()}
              </Link>
            </li>
          </ul>
        </section>
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4">{m['sitemap.sections.content']()}</h2>
          <ul className="space-y-2">
            <li>
              <Link to="/ko/news" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.news']()}
              </Link>
            </li>
            <li>
              <Link to="/ko/blog" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.blog']()}
              </Link>
            </li>
            <li>
              <Link to="/ko/sound-recording" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.soundRecording']()}
              </Link>
            </li>
          </ul>
        </section>
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4">{m['sitemap.sections.legal']()}</h2>
          <ul className="space-y-2">
            <li>
              <Link to="/ko/privacy" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.privacy']()}
              </Link>
            </li>
            <li>
              <Link to="/ko/terms" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.terms']()}
              </Link>
            </li>
            <li>
              <Link to="/ko/license" className="text-[var(--color-link)] hover:underline">
                {m['sitemap.links.license']()}
              </Link>
            </li>
          </ul>
        </section>
        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-4">{m['sitemap.sections.other']()}</h2>
          <ul className="space-y-2">
            <li>
              <a
                href="/sitemap.xml"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[var(--color-link)] hover:underline"
              >
                {m['sitemap.xml']()}
              </a>
            </li>
          </ul>
        </section>
      </div>
    </NavigationLayout>
  );
}
