// apps/sound-blue/app/components/background/CSSParticles.tsx
/**
 * Pure CSS particle background - no JavaScript, no click blocking issues
 */
export function CSSParticles() {
  return (
    <div className="css-particles" aria-hidden="true">
      <div className="particle particle-1" />
      <div className="particle particle-2" />
      <div className="particle particle-3" />
      <div className="particle particle-4" />
      <div className="particle particle-5" />
      <div className="particle particle-6" />
      <div className="particle particle-7" />
      <div className="particle particle-8" />
      <div className="particle particle-9" />
      <div className="particle particle-10" />
      <div className="particle particle-11" />
      <div className="particle particle-12" />
    </div>
  );
}

// apps/sound-blue-solid-backup/src/components/background/CSSParticles.tsx
import type { JSX } from 'solid-js';

/**
 * Pure CSS particle background - no JavaScript, no click blocking issues
 */
export function CSSParticles(): JSX.Element {
  return (
    <div class="css-particles" aria-hidden="true">
      <div class="particle particle-1" />
      <div class="particle particle-2" />
      <div class="particle particle-3" />
      <div class="particle particle-4" />
      <div class="particle particle-5" />
      <div class="particle particle-6" />
      <div class="particle particle-7" />
      <div class="particle particle-8" />
      <div class="particle particle-9" />
      <div class="particle particle-10" />
      <div class="particle particle-11" />
      <div class="particle particle-12" />
    </div>
  );
}
