// apps/sound-blue/src/components/layout/Header.tsx
import { useParaglideI18n } from '@soundblue/i18n';
import { ColorblindSelector, useTheme } from '@soundblue/ui-components/base';
import { ServiceMenu } from '@soundblue/ui-components/composite';
import { Link } from '@tanstack/react-router';
import { SearchBox, ThemeIcon } from '~/components/ui';
import m from '~/lib/messages';

interface HeaderProps {
  onSidebarToggle?: () => void;
  isSidebarOpen?: boolean;
}

export function Header({ onSidebarToggle, isSidebarOpen = true }: HeaderProps) {
  const { toggleLanguage, localizedPath, locale } = useParaglideI18n();
  const { resolvedTheme, toggleTheme } = useTheme();
  const currentLocale = locale === 'ko' ? 'ko' : 'en';

  const themeTitle = resolvedTheme === 'light' ? m['header.themeDark']() : m['header.themeLight']();

  return (
    <header className="fixed inset-x-0 top-0 z-[100] h-[var(--header-height)] bg-[var(--color-bg-secondary)] border-b border-[var(--color-border-primary)] supports-[padding:env(safe-area-inset-top)]:pt-[env(safe-area-inset-top)] supports-[padding:env(safe-area-inset-top)]:h-[calc(56px+env(safe-area-inset-top))] max-md:h-[52px] max-md:supports-[padding:env(safe-area-inset-top)]:h-[calc(52px+env(safe-area-inset-top))]">
      <div className="flex items-center gap-4 w-full h-full px-4 pl-[calc(var(--sidebar-width)+16px)] max-md:px-3 max-md:gap-2">
        {/* Sidebar Toggle - Desktop only */}
        {onSidebarToggle && (
          <button
            type="button"
            onClick={onSidebarToggle}
            className="absolute left-4 top-1/2 -translate-y-1/2 hidden md:inline-flex items-center justify-center w-10 h-10 p-0 rounded-xl text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-interactive-hover)] active:bg-[var(--color-interactive-active)] transition-colors duration-150 cursor-pointer border-none bg-transparent focus-visible:outline-2 focus-visible:outline-[var(--color-border-focus)] focus-visible:outline-offset-2 max-md:w-9 max-md:h-9"
            title={isSidebarOpen ? m['header.sidebarClose']() : m['header.sidebarOpen']()}
            aria-label={isSidebarOpen ? m['header.sidebarClose']() : m['header.sidebarOpen']()}
            aria-expanded={isSidebarOpen}
          >
            <svg
              className="w-[1.125rem] h-[1.125rem] shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              width="20"
              height="20"
            >
              {isSidebarOpen ? (
                <>
                  <rect x="3" y="3" width="18" height="18" rx="2" strokeWidth="2" />
                  <path strokeWidth="2" d="M9 3v18" />
                </>
              ) : (
                <>
                  <rect x="3" y="3" width="18" height="18" rx="2" strokeWidth="2" />
                  <path strokeWidth="2" d="M9 3v18" />
                  <path strokeWidth="2" strokeLinecap="round" d="M14 9l3 3-3 3" />
                </>
              )}
            </svg>
          </button>
        )}

        {/* Logo */}
        <Link
          to={localizedPath('/')}
          className="flex items-center gap-1.5 no-underline shrink-0 rounded-xl focus-visible:outline-2 focus-visible:outline-[var(--color-border-focus)] focus-visible:outline-offset-2"
        >
          <span className="text-xl font-semibold text-[var(--color-text-primary)] tracking-tight max-md:text-lg">
            Sound Blue
          </span>
        </Link>

        {/* Search */}
        <SearchBox />

        {/* Spacer */}
        <div className="flex-1" />

        {/* Controls */}
        <div className="flex items-center gap-2 shrink-0">
          {/* Service Menu */}
          <ServiceMenu currentApp="sound-blue" locale={currentLocale} />
          {/* Colorblind Mode Selector */}
          <ColorblindSelector locale={currentLocale} />
          {/* Theme Toggle */}
          <button
            type="button"
            onClick={toggleTheme}
            className="inline-flex items-center justify-center min-w-11 min-h-11 w-11 h-11 p-0 rounded-xl text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-interactive-hover)] active:bg-[var(--color-interactive-active)] transition-colors duration-150 cursor-pointer border-none bg-transparent focus-visible:outline-2 focus-visible:outline-[var(--color-border-focus)] focus-visible:outline-offset-2"
            title={themeTitle}
            aria-label={themeTitle}
          >
            <ThemeIcon theme={resolvedTheme as 'light' | 'dark'} />
          </button>

          {/* Language Toggle */}
          <button
            type="button"
            onClick={toggleLanguage}
            className="inline-flex items-center justify-center gap-1.5 min-w-11 min-h-11 h-11 px-3 rounded-xl text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] hover:bg-[var(--color-interactive-hover)] active:bg-[var(--color-interactive-active)] transition-colors duration-150 cursor-pointer border-none bg-transparent focus-visible:outline-2 focus-visible:outline-[var(--color-border-focus)] focus-visible:outline-offset-2"
            title={m['header.langSwitch']()}
            aria-label={`${m['header.langSwitch']()} (${m['header.langCode']()})`}
          >
            <svg
              className="w-5 h-5 shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              aria-hidden="true"
            >
              <circle cx="12" cy="12" r="10" />
              <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
            </svg>
            <span className="text-sm font-semibold tracking-wide" aria-hidden="true">
              {m['header.langCode']()}
            </span>
          </button>
        </div>
      </div>
    </header>
  );
}

// apps/sound-blue/src/components/Header.tsx
import { A } from '@solidjs/router';
import type { JSX } from 'solid-js';
import { useLanguage, useTheme } from '~/components/providers';
import { ToolsIcon } from '~/constants/icons';
import { SearchBox, ThemeIcon } from './ui';

interface HeaderProps {
  onSidebarToggle?: () => void;
  isSidebarOpen?: boolean;
}

export function Header(props: HeaderProps): JSX.Element {
  const { t, toggleLanguage, localizedPath } = useLanguage();
  const { theme, toggleTheme } = useTheme();

  const isSidebarOpen = () => props.isSidebarOpen ?? true;

  const themeTitle = () => (theme() === 'light' ? t().header.themeDark : t().header.themeLight);

  return (
    <header class="view-transition-header fixed top-0 left-0 right-0 z-[100] h-14 bg-surface-alt border-b border-line supports-[padding:env(safe-area-inset-top)]:pt-[env(safe-area-inset-top)] supports-[padding:env(safe-area-inset-top)]:h-[calc(56px+env(safe-area-inset-top))] max-sm:h-13 max-sm:supports-[padding:env(safe-area-inset-top)]:h-[calc(52px+env(safe-area-inset-top))]">
      <div class="flex items-center gap-4 w-full h-full px-4 md:pl-[calc(var(--sidebar-width)+16px)] max-sm:px-3 max-sm:gap-2">
        {/* Sidebar Toggle - Desktop only */}
        {props.onSidebarToggle && (
          <button
            type="button"
            onClick={props.onSidebarToggle}
            class="hidden md:inline-flex absolute left-4 top-1/2 -translate-y-1/2 items-center justify-center w-10 h-10 p-0 bg-transparent rounded-lg text-content-muted hover:bg-state-hover hover:text-content focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent active:scale-95 transition-all duration-150 max-sm:w-9 max-sm:h-9"
            title={isSidebarOpen() ? t().header.sidebarClose : t().header.sidebarOpen}
            aria-label={isSidebarOpen() ? t().header.sidebarClose : t().header.sidebarOpen}
            aria-expanded={isSidebarOpen()}
          >
            <svg
              class="w-[18px] h-[18px] shrink-0"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              width="20"
              height="20"
            >
              {isSidebarOpen() ? (
                <>
                  <rect x="3" y="3" width="18" height="18" rx="2" stroke-width="2" />
                  <path stroke-width="2" d="M9 3v18" />
                </>
              ) : (
                <>
                  <rect x="3" y="3" width="18" height="18" rx="2" stroke-width="2" />
                  <path stroke-width="2" d="M9 3v18" />
                  <path stroke-width="2" stroke-linecap="round" d="M14 9l3 3-3 3" />
                </>
              )}
            </svg>
          </button>
        )}

        {/* Logo */}
        <A
          href={localizedPath('/')}
          class="flex items-center gap-1.5 no-underline shrink-0 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
        >
          <span class="text-xl font-semibold text-content tracking-tight max-sm:text-lg">
            Sound Blue
          </span>
        </A>

        {/* Search */}
        <SearchBox />

        {/* Spacer */}
        <div class="flex-1" />

        {/* Tools Button */}
        <a
          href="https://tools.soundbluemusic.com"
          target="_blank"
          rel="noopener noreferrer"
          class="hidden sm:inline-flex items-center justify-center gap-1.5 h-9 px-3 bg-accent/10 hover:bg-accent/20 text-accent rounded-lg text-sm font-medium transition-all duration-150 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
          title="Tools"
        >
          <ToolsIcon class="w-4 h-4" />
          <span>Tools</span>
        </a>

        {/* Controls */}
        <div class="flex items-center gap-2 shrink-0">
          {/* Theme Toggle */}
          <button
            type="button"
            onClick={toggleTheme}
            class="inline-flex items-center justify-center w-10 h-10 p-0 bg-transparent rounded-lg text-content-muted hover:bg-state-hover hover:text-content focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent active:scale-95 transition-all duration-150 max-sm:w-9 max-sm:h-9"
            title={themeTitle()}
            aria-label={themeTitle()}
          >
            <ThemeIcon theme={theme()} />
          </button>

          {/* Language Toggle */}
          <button
            type="button"
            onClick={toggleLanguage}
            class="inline-flex items-center justify-center gap-1 w-auto h-10 px-3 bg-transparent rounded-lg text-content-muted hover:bg-state-hover hover:text-content focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent active:scale-95 transition-all duration-150 max-sm:h-9 max-sm:px-2"
            title={t().header.langSwitch}
            aria-label={t().header.langSwitch}
          >
            <svg
              class="w-4 h-4 shrink-0"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
            >
              <circle cx="12" cy="12" r="10" />
              <path d="M2 12h20M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
            </svg>
            <span class="text-xs font-semibold tracking-wide">{t().header.langCode}</span>
          </button>
        </div>
      </div>
    </header>
  );
}
