// apps/tools/src/routes/index.tsx
import { BreadcrumbStructuredData } from '@soundblue/seo';
import { createFileRoute } from '@tanstack/react-router';
import { useEffect } from 'react';
import { HomeLayout } from '~/components/layout';
import { useToolStore } from '~/stores/tool-store';

export const Route = createFileRoute('/')({
  head: () => ({
    meta: [
      { title: 'Tools - SoundBlueMusic' },
      {
        name: 'description',
        content: 'Pro-grade Web DAW, Rhythm Game & Creative Tools for musicians and creators.',
      },
      {
        name: 'keywords',
        content:
          'music tools, web daw, metronome, drum machine, qr generator, translator, online tools',
      },
    ],
  }),
  component: HomePage,
});

function HomePage() {
  const closeTool = useToolStore((state) => state.closeTool);

  useEffect(() => {
    closeTool();
  }, [closeTool]);

  return (
    <>
      <BreadcrumbStructuredData
        items={[{ name: 'Tools', url: 'https://tools.soundbluemusic.com' }]}
      />
      <HomeLayout />
    </>
  );
}

// apps/tools-solid-backup/src/routes/index.tsx
import { Link, Meta, Title } from '@solidjs/meta';
import { onMount } from 'solid-js';
import { HomeLayout } from '~/components/layout';
import { toolActions } from '~/stores/tool-store';

// Import tools to trigger registration
import '~/tools';

const SITE_URL = 'https://tools.soundbluemusic.com';

export default function Home() {
  // Close any open tool when navigating to home
  onMount(() => {
    toolActions.closeTool();
  });

  return (
    <>
      <Title>Tools - SoundBlueMusic</Title>
      <Meta
        name="description"
        content="Pro-grade Web DAW, Rhythm Game & Creative Tools for musicians and creators. 음악가와 크리에이터를 위한 웹 DAW, 리듬 게임 및 창작 도구."
      />
      <Link rel="canonical" href={SITE_URL} />
      {/* Open Graph */}
      <Meta property="og:url" content={SITE_URL} />
      {/* Alternate Languages */}
      <Link rel="alternate" hreflang="en" href={SITE_URL} />
      <Link rel="alternate" hreflang="ko" href={`${SITE_URL}/ko`} />
      <Link rel="alternate" hreflang="x-default" href={SITE_URL} />
      <HomeLayout />
    </>
  );
}
