// packages/ui/patterns/src/chat/ChatMessage.tsx
// ========================================
// @soundblue/ui-patterns - ChatMessage
// Individual chat message component
// ========================================

import type { ReactNode } from 'react';

export type MessageRole = 'user' | 'assistant' | 'system';

export interface ChatMessageProps {
  role: MessageRole;
  content: ReactNode;
  timestamp?: Date;
  className?: string;
}

/**
 * Individual chat message
 */
export function ChatMessage({ role, content, timestamp, className = '' }: ChatMessageProps) {
  const isUser = role === 'user';
  const isSystem = role === 'system';

  return (
    <li
      className={`
        flex w-full list-none
        ${isUser ? 'justify-end' : 'justify-start'}
        ${isSystem ? 'justify-center' : ''}
        ${className}
      `}
    >
      <div
        className={`
          max-w-[80%] rounded-lg px-4 py-2
          ${isUser ? 'bg-blue-500 text-white' : ''}
          ${role === 'assistant' ? 'bg-gray-100 dark:bg-gray-800' : ''}
          ${isSystem ? 'bg-yellow-50 dark:bg-yellow-900/20 text-sm text-gray-600 dark:text-gray-400' : ''}
        `}
      >
        <div className="whitespace-pre-wrap">{content}</div>
        {timestamp && (
          <time
            className={`
              block mt-1 text-xs opacity-70
              ${isUser ? 'text-right' : 'text-left'}
            `}
            dateTime={timestamp.toISOString()}
          >
            {timestamp.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
          </time>
        )}
      </div>
    </li>
  );
}

// apps/sound-blue-solid-backup/src/components/chat/ChatMessage.tsx
import type { JSX } from 'solid-js';
import { cn } from '~/lib/utils';

export interface Message {
  id: string;
  type: 'user' | 'bot';
  content: string;
  timestamp: number;
}

interface ChatMessageProps {
  message: Message;
}

export function ChatMessage(props: ChatMessageProps): JSX.Element {
  const isBot = () => props.message.type === 'bot';

  return (
    <li class={cn('flex w-full list-none', isBot() ? 'justify-start' : 'justify-end')}>
      <div
        class={cn(
          'max-w-[80%] px-4 py-2.5 rounded-2xl text-sm leading-relaxed',
          isBot()
            ? 'bg-surface-alt text-content rounded-bl-md'
            : 'bg-accent text-white rounded-br-md',
        )}
      >
        {props.message.content}
      </div>
    </li>
  );
}
