// apps/tools/src/components/layout/Footer.tsx
import type { Component } from 'solid-js';

// ========================================
// Footer Component - 푸터
// ========================================

export const Footer: Component = () => {
  return (
    <footer class="border-t bg-background px-4 py-2 pb-[max(0.5rem,env(safe-area-inset-bottom))]">
      <p class="text-center text-xs text-muted-foreground">UI/UX based on web standards</p>
      <p class="text-center text-xs text-muted-foreground">
        Tools by{' '}
        <a
          href="https://soundbluemusic.com"
          target="_blank"
          rel="noopener noreferrer"
          class="text-primary transition-all duration-200 hover:underline hover:text-primary/70 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 rounded-sm"
        >
          SoundBlueMusic
        </a>
      </p>
    </footer>
  );
};

// apps/tools/app/components/layout/Footer.tsx
/**
 * @fileoverview Footer component for Tools app
 *
 * A simple footer component.
 */

interface FooterProps {
  appName?: string;
  brandName?: string;
  brandUrl?: string;
  tagline?: string;
  className?: string;
}

export function Footer({
  appName = 'Tools',
  brandName = 'SoundBlueMusic',
  brandUrl = 'https://soundbluemusic.com',
  tagline,
  className = '',
}: FooterProps) {
  return (
    <footer
      className={`border-t bg-background px-4 py-2 pb-[max(0.5rem,env(safe-area-inset-bottom))] ${className}`}
    >
      {/* Tagline */}
      {tagline && <p className="text-center text-xs text-muted-foreground mb-1">{tagline}</p>}

      {/* App name and brand */}
      <p className="text-center text-xs text-muted-foreground">
        {appName} by{' '}
        <a
          href={brandUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="text-primary transition-all duration-200 hover:underline hover:opacity-80"
        >
          {brandName}
        </a>
      </p>
    </footer>
  );
}
