// apps/dialogue/src/components/chat/ChatMessage.tsx
import { memo, useEffect, useRef, useState } from 'react';
import m from '~/lib/messages';
import type { Message } from '~/stores';

interface ChatMessageProps {
  message: Message;
}

/**
 * 성능: React.memo로 불필요한 리렌더링 방지
 */
export const ChatMessage = memo(function ChatMessage({ message }: ChatMessageProps) {
  const isUser = message.role === 'user';
  const [copied, setCopied] = useState(false);
  const timeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Cleanup timeout on unmount
  useEffect(() => {
    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
    };
  }, []);

  const handleCopy = async () => {
    // Clear any existing timeout
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current);
    }

    try {
      await navigator.clipboard.writeText(message.content);
      setCopied(true);
      timeoutRef.current = setTimeout(() => setCopied(false), 1500);
    } catch {
      // Fallback for older browsers
      const textArea = document.createElement('textarea');
      textArea.value = message.content;
      document.body.appendChild(textArea);
      textArea.select();
      document.execCommand('copy');
      document.body.removeChild(textArea);
      setCopied(true);
      timeoutRef.current = setTimeout(() => setCopied(false), 1500);
    }
  };

  return (
    <div
      className={`group flex gap-2 animate-[fadeIn_0.3s_ease-out] ${isUser ? 'flex-row-reverse' : 'flex-row'}`}
    >
      {/* Avatar */}
      <div
        className={`w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-sm font-medium ${
          isUser
            ? 'bg-[var(--color-accent-primary)] text-white'
            : 'bg-[var(--color-bg-tertiary)] text-[var(--color-text-secondary)]'
        }`}
      >
        {isUser ? 'U' : 'D'}
      </div>

      {/* Message content */}
      <div
        className={`max-w-[70%] px-4 py-2 rounded-2xl ${
          isUser
            ? 'bg-[var(--color-accent-primary)] text-white rounded-br-md'
            : 'bg-[var(--color-bg-tertiary)] text-[var(--color-text-primary)] rounded-bl-md'
        }`}
      >
        <p className="whitespace-pre-wrap break-words">{message.content}</p>
      </div>

      {/* Copy button */}
      <button
        type="button"
        onClick={handleCopy}
        className={`self-center p-1.5 rounded-md border-none cursor-pointer transition-all duration-150 focus:outline-2 focus:outline-[var(--color-border-focus)] focus:outline-offset-2 ${
          copied
            ? 'bg-green-500/15 text-green-600 dark:text-green-400'
            : 'bg-transparent text-[var(--color-text-tertiary)] hover:bg-[var(--color-bg-tertiary)] hover:text-[var(--color-text-secondary)]'
        }`}
        title={copied ? m['app.copied']() : m['app.copy']()}
      >
        {copied ? <CheckIcon /> : <CopyIcon />}
      </button>
    </div>
  );
});

function CopyIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" width="14" height="14">
      <path d="M16 1H4c-1.1 0-2 .9-2 2v14h2V3h12V1zm3 4H8c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h11c1.1 0 2-.9 2-2V7c0-1.1-.9-2-2-2zm0 16H8V7h11v14z" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" width="14" height="14">
      <path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z" />
    </svg>
  );
}

// apps/dialogue/src/components/ChatMessage.tsx
import { Component, Show } from "solid-js";

export interface Message {
  id: string;
  role: "user" | "assistant";
  content: string;
  timestamp: number;
}

interface ChatMessageProps {
  message: Message;
}

export const ChatMessage: Component<ChatMessageProps> = (props) => {
  const isUser = () => props.message.role === "user";

  return (
    <div
      class="flex gap-3 px-6 py-4 animate-fade-in max-md:px-4 max-md:py-3"
      classList={{ "flex-row-reverse": isUser() }}
    >
      <div
        class="w-9 h-9 rounded-full flex items-center justify-center shrink-0"
        classList={{
          "bg-accent text-white": isUser(),
          "bg-assistant-bubble text-accent": !isUser()
        }}
      >
        <Show when={isUser()} fallback={<AssistantIcon />}>
          <UserIcon />
        </Show>
      </div>
      <div
        class="max-w-[70%] px-4 py-3 rounded-[--radius-md] leading-normal max-md:max-w-[85%]"
        classList={{
          "bg-user-bubble text-white rounded-br-[4px]": isUser(),
          "bg-assistant-bubble text-text-primary rounded-bl-[4px]": !isUser()
        }}
      >
        <p class="m-0 whitespace-pre-wrap break-words">{props.message.content}</p>
      </div>
    </div>
  );
};

const UserIcon = () => (
  <svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20">
    <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
  </svg>
);

const AssistantIcon = () => (
  <svg viewBox="0 0 24 24" fill="currentColor" width="20" height="20">
    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z" />
  </svg>
);
