// apps/sound-blue/app/routes/about.tsx
import type { MetaFunction } from 'react-router';
import { NavigationLayout } from '~/components/layout';
import m, { getRawMessage } from '~/lib/messages';
export const meta: MetaFunction = () => [
  { title: 'About | Sound Blue' },
  {
    name: 'description',
    content: 'About Sound Blue and SoundBlueMusic. Learn more about the artist, music, and vision.',
  },
];

export default function About() {
  return (
    <NavigationLayout>
      <div className="max-w-3xl mx-auto p-6">
        <h1 className="text-3xl font-bold text-content mb-6">{m['about.title']()}</h1>
        <p className="text-lg text-content-muted mb-8">{m['about.intro']()}</p>

        <section className="prose mb-8">
          <h2>{m['about.sections.artist.title']()}</h2>
          <p>{m['about.sections.artist.content']()}</p>
        </section>

        <section className="prose mb-8">
          <h2>{m['about.sections.label.title']()}</h2>
          <p>{m['about.sections.label.content']()}</p>
        </section>

        <section className="prose mb-8">
          <h2>{m['about.sections.music.title']()}</h2>
          <p>{m['about.sections.music.content']()}</p>
        </section>

        <section className="prose mb-8">
          <h2>{m['about.sections.vision.title']()}</h2>
          <p>{m['about.sections.vision.content']()}</p>
        </section>

        <section className="prose mb-8">
          <h2>{m['about.sections.projects.title']()}</h2>
          <ul>
            {(getRawMessage('about_sections_projects_items') as string[] | undefined)?.map(
              (item, index) => (
                <li key={index}>{item}</li>
              ),
            )}
          </ul>
        </section>

        <section className="prose mb-8">
          <h2>{m['about.sections.connect.title']()}</h2>
          <ul>
            <li>
              <a
                href="https://youtube.com/@SoundBlueMusic"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline dark:text-blue-400"
              >
                {m['about.sections.connect.youtube']()}
              </a>
            </li>
            <li>
              <a
                href="https://github.com/soundbluemusic"
                target="_blank"
                rel="noopener noreferrer"
                className="text-blue-600 hover:underline dark:text-blue-400"
              >
                {m['about.sections.connect.github']()}
              </a>
            </li>
          </ul>
        </section>
      </div>
    </NavigationLayout>
  );
}

// apps/sound-blue-solid-backup/src/routes/about.tsx
import type { JSX } from 'solid-js';
import { NavigationLayout, OptimizedImage, PageSeo, useLanguage } from '~/components';
import { LinkButton } from '~/components/ui';
import { YouTubeIcon } from '~/constants';

export default function AboutPage(): JSX.Element {
  const { t } = useLanguage();

  return (
    <>
      <PageSeo page="about" />
      <NavigationLayout>
        <div class="w-full bg-white/80 dark:bg-white/10 py-6 sm:py-8 mb-8">
          <div class="flex justify-center items-center px-4">
            <OptimizedImage
              src="/branding-assets/logo-mascot-nb"
              alt="Sound Blue Mascot"
              width={800}
              height={434}
              sizes={[400, 600, 800]}
              sizesAttr="(max-width: 640px) 90vw, (max-width: 1024px) 600px, 800px"
              pictureClass="w-full max-w-md sm:max-w-lg lg:max-w-2xl transition-all duration-300 ease-out"
              class="w-full h-auto object-contain transition-all duration-300 ease-out"
              priority
            />
          </div>
        </div>
        <div class="max-w-4xl mx-auto px-4 py-8">
          <h1 class="text-3xl font-bold mb-2">{t().about.title}</h1>
          <p class="text-xl text-content-muted mb-8">{t().about.subtitle}</p>

          <div class="prose prose-lg max-w-none">
            <p class="mb-8 text-lg text-content-muted">{t().about.intro}</p>

            <h2 class="text-xl font-semibold mt-8 mb-4">{t().about.sections.artist.title}</h2>
            <p class="mb-4">{t().about.sections.artist.content}</p>

            <h2 class="text-xl font-semibold mt-8 mb-4">{t().about.sections.label.title}</h2>
            <p class="mb-4">{t().about.sections.label.content}</p>

            <h2 class="text-xl font-semibold mt-8 mb-4">{t().about.sections.music.title}</h2>
            <p class="mb-4">{t().about.sections.music.content}</p>

            <h2 class="text-xl font-semibold mt-8 mb-4">{t().about.sections.vision.title}</h2>
            <p class="mb-4">{t().about.sections.vision.content}</p>

            <h2 class="text-xl font-semibold mt-8 mb-4">{t().about.sections.connect.title}</h2>
            <div class="flex flex-wrap gap-4">
              <LinkButton
                href="https://www.youtube.com/@SoundBlueMusic"
                target="_blank"
                rel="noopener noreferrer"
                variant="youtube"
                size="md"
                class="gap-2"
              >
                <YouTubeIcon class="w-5 h-5" />
                {t().about.sections.connect.youtube}
              </LinkButton>
            </div>
          </div>
        </div>
      </NavigationLayout>
    </>
  );
}
