// apps/sound-blue/src/routes/privacy.tsx
import { createFileRoute } from '@tanstack/react-router';
import { NavigationLayout } from '~/components/layout';
import m from '~/lib/messages';
import { generateSeoMeta } from '~/lib/seo';

export const Route = createFileRoute('/privacy')({
  head: () => ({
    meta: [
      { title: 'Privacy Policy | Sound Blue' },
      { name: 'description', content: "Sound Blue's privacy policy." },
      ...generateSeoMeta('/privacy'),
    ],
  }),
  component: Privacy,
});

function Privacy() {
  return (
    <NavigationLayout>
      <div className="max-w-3xl mx-auto p-6 prose">
        <h1>{m['privacy.title']()}</h1>
        <h2>{m['privacy.sections.collection.title']()}</h2>
        <p>{m['privacy.sections.collection.content']()}</p>
        <h2>{m['privacy.sections.cookies.title']()}</h2>
        <p>{m['privacy.sections.cookies.content']()}</p>
        <h2>{m['privacy.sections.thirdParty.title']()}</h2>
        <p>{m['privacy.sections.thirdParty.content']()}</p>
        <h2>{m['privacy.sections.contact.title']()}</h2>
        <p>{m['privacy.sections.contact.content']()}</p>
      </div>
    </NavigationLayout>
  );
}

// apps/sound-blue-solid-backup/src/routes/privacy.tsx
import type { JSX } from 'solid-js';
import { NavigationLayout, PageSeo, useLanguage } from '~/components';

export default function PrivacyPage(): JSX.Element {
  const { t } = useLanguage();

  return (
    <>
      <PageSeo page="privacy" />
      <NavigationLayout>
        <div class="max-w-4xl mx-auto px-4 py-8">
          <h1 class="text-3xl font-bold mb-8">{t().privacy.title}</h1>

          <div class="prose prose-lg max-w-none">
            <p class="text-content-muted mb-6">{t().common.lastUpdated}</p>
            <h2 class="text-xl font-semibold mt-8 mb-4">{t().privacy.sections.collection.title}</h2>
            <p class="mb-4">{t().privacy.sections.collection.content}</p>
            <h2 class="text-xl font-semibold mt-8 mb-4">{t().privacy.sections.cookies.title}</h2>
            <p class="mb-4">{t().privacy.sections.cookies.content}</p>
            <h2 class="text-xl font-semibold mt-8 mb-4">{t().privacy.sections.thirdParty.title}</h2>
            <p class="mb-4">{t().privacy.sections.thirdParty.content}</p>
            <h2 class="text-xl font-semibold mt-8 mb-4">{t().privacy.sections.contact.title}</h2>
            <p class="mb-4">{t().privacy.sections.contact.content}</p>
          </div>
        </div>
      </NavigationLayout>
    </>
  );
}
